---
  - name: "Install nginx"
    hosts: webserver
    become: yes
    tasks:
      - name: "Apt get nginx"
        apt:
          name: nginx
          state: present
      - name: "Copy nginx config"
        copy:
          src: files/nginx_prod.conf
          dest: /etc/nginx/sites-enabled/default
      - name: "Restart nginx service"
        command: service nginx restart

