name: Build and deploy frontend

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./public/dist

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 89.208.197.150
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./build/*"
          target: "/home/ubuntu/frontend/public/dist"
          strip_components: 1
